[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
remappings = ["forge-std/=lib/forge-std/src/"]

[rpc_endpoints]
# Used by forge script. Override with --rpc-url or env ETH_RPC_URL
mainnet = "${ETH_RPC_URL}"
sepolia = "${ETH_RPC_URL}"

[etherscan]
# Override with --verify or env ETHERSCAN_API_KEY
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
